feat: make sure release only happens on default_branch like main (#87)
Co-authored-by: Ben Drucker <bvdrucker@gmail.com>

diff --git a/.github/workflows/terraform-observe_release.yaml b/.github/workflows/terraform-observe_release.yaml
--- a/.github/workflows/terraform-observe_release.yaml
+++ b/.github/workflows/terraform-observe_release.yaml
@@ -24,6 +24,11 @@ jobs:
       contents: write
       pull-requests: write
     steps:
+      - name: Check branch
+        if: github.ref_type != 'branch' || github.ref_name != github.event.repository.default_branch
+        run: |
+          echo "::error::release job must be run from the default_branch (${{ github.event.repository.default_branch }}). Found ${{ github.ref_name }}."
+          exit 1
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
